### PR TITLE
Added Emojify Options to Website

### PR DESCRIPTION
**Pull request by LapisPhoenix**
- Added Random
- Added Size
- Added Delay

### CODE REVIEW

**Comment by GreenestGoat** [comment]
Gonna merge soon just finishing up the touches on the ui

**Comment by TheoOliveira** [comment]
great stuff, I'd change the delay to be way more then that is now for the codepen and website. Another question, is it possible to make it like only show accordingly where i want to show? I'd be useful..

**Comment by GreenestGoat** [comment]
yes that defo a feature ive been planning adding where you specfy an id / class or elkement then it will only show in that elemnt of when hovering there by default it sets it body

**Comment by GreenestGoat** [comment]
i also added a editor on the demo page so you can customize the values of delay, duration and zindex currently

**Pull request closed without merging**
